In [1]:
import pandas as pd

In [2]:
# ---------- Load CSV files from data/raw ----------
btc  = pd.read_csv("../data/raw/BTC-USD.csv")
eth  = pd.read_csv("../data/raw/ETH-USD.csv")
bnb  = pd.read_csv("../data/raw/BNB-USD.csv")
ada  = pd.read_csv("../data/raw/ADA-USD.csv")
doge = pd.read_csv("../data/raw/DOGE-USD.csv")
dot  = pd.read_csv("../data/raw/DOT-USD.csv")
sol  = pd.read_csv("../data/raw/SOL-USD.csv")
xrp  = pd.read_csv("../data/raw/XRP-USD.csv")
ltc  = pd.read_csv("../data/raw/LTC-USD.csv")
bch  = pd.read_csv("../data/raw/BCH-USD.csv")

In [3]:
# ---------- Add crypto name column ----------
btc['crypto']  = 'BTC'
eth['crypto']  = 'ETH'
bnb['crypto']  = 'BNB'
ada['crypto']  = 'ADA'
doge['crypto'] = 'DOGE'
dot['crypto']  = 'DOT'
sol['crypto']  = 'SOL'
xrp['crypto']  = 'XRP'
ltc['crypto']  = 'LTC'
bch['crypto']  = 'BCH'

In [4]:
# ---------- Combine all data ----------
master_df = pd.concat(
    [btc, eth, bnb, ada, doge, dot, sol, xrp, ltc, bch],
    ignore_index=True
)

In [5]:
# ---------- Date handling ----------
master_df['Date'] = pd.to_datetime(master_df['Date'])
master_df.sort_values(by=['crypto', 'Date'], inplace=True)

In [6]:
master_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,crypto
1287,2020-12-31,0.184034,0.185749,0.176594,0.181397,0.181397,1132268397,ADA
1288,2021-01-01,0.181382,0.184246,0.172022,0.175350,0.175350,1122218004,ADA
1289,2021-01-02,0.175359,0.184253,0.169233,0.177423,0.177423,1408849504,ADA
1290,2021-01-03,0.177382,0.208679,0.173376,0.204995,0.204995,2303857909,ADA
1291,2021-01-04,0.205236,0.239661,0.194450,0.224762,0.224762,3260699086,ADA

In [7]:
master_df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume,crypto
3391,2022-02-28,0.721931,0.788322,0.713188,0.782044,0.782044,3053923291,XRP
3392,2022-03-01,0.782070,0.800635,0.761234,0.784862,0.784862,2877778057,XRP
3393,2022-03-02,0.784876,0.784891,0.759598,0.768496,0.768496,2401047273,XRP
3394,2022-03-03,0.768532,0.783925,0.738920,0.752185,0.752185,2213014779,XRP
3395,2022-03-06,0.755771,0.757829,0.730040,0.734885,0.734885,1765211008,XRP

In [8]:
master_df['crypto'].value_counts()

crypto
ADA     429
BCH     429
BNB     429
BTC     429
DOGE    429
ETH     429
SOL     429
LTC     429
XRP     429
DOT     393
Name: count, dtype: int64

In [9]:
# ---------- Save processed master file ----------
master_df.to_csv("../data/processed/crypto_master_data.csv", index=False)