In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("crypto_master_data.csv")
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,crypto
0,2020-12-31,0.184034,0.185749,0.176594,0.181397,0.181397,1132268397,ADA
1,2021-01-01,0.181382,0.184246,0.172022,0.175350,0.175350,1122218004,ADA
2,2021-01-02,0.175359,0.184253,0.169233,0.177423,0.177423,1408849504,ADA
3,2021-01-03,0.177382,0.208679,0.173376,0.204995,0.204995,2303857909,ADA
4,2021-01-04,0.205236,0.239661,0.194450,0.224762,0.224762,3260699086,ADA

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4254 entries, 0 to 4253
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       4254 non-null   object
 1   Open       4254 non-null   float64
 2   High       4254 non-null   float64
 3   Low        4254 non-null   float64
 4   Close      4254 non-null   float64
 5   Adj Close  4254 non-null   float64
 6   Volume     4254 non-null   int64
 7   crypto     4254 non-null   object
dtypes: float64(5), int64(1), object(2)
memory usage: 266.0+ KB

In [4]:
df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
crypto       0
dtype: int64

In [5]:
master_df = df[
    ['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'crypto']
]

In [6]:
master_df.rename(columns={
    'Open': 'open_price',
    'High': 'high_price',
    'Low': 'low_price',
    'Close': 'close_price',
    'Volume': 'volume'
}, inplace=True)

C:\Users\shind\AppData\Local\Temp\ipykernel_12656\1207256632.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df.rename(columns={

In [7]:
master_df.sort_values(by=['crypto', 'Date'], inplace=True)

C:\Users\shind\AppData\Local\Temp\ipykernel_12656\1125531844.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df.sort_values(by=['crypto', 'Date'], inplace=True)

In [8]:
master_df.set_index('Date', inplace=True)

In [9]:
master_df.head()

            open_price  high_price  low_price  close_price      volume crypto
Date
2020-12-31    0.184034    0.185749   0.176594     0.181397  1132268397    ADA
2021-01-01    0.181382    0.184246   0.172022     0.175350  1122218004    ADA
2021-01-02    0.175359    0.184253   0.169233     0.177423  1408849504    ADA
2021-01-03    0.177382    0.208679   0.173376     0.204995  2303857909    ADA
2021-01-04    0.205236    0.239661   0.194450     0.224762  3260699086    ADA

In [10]:
master_df.groupby('crypto').size()

crypto
ADA     429
BCH     429
BNB     429
BTC     429
DOGE    429
DOT     393
ETH     429
LTC     429
SOL     429
XRP     429
dtype: int64

In [11]:
master_df.to_csv("crypto_master_cleaned.csv")